language: csharp
solution: NuBus.sln
services:
  - rabbitmq

install:
  - nuget restore NuBus.sln
  - nuget install NUnit.Runners -Version 3.5.0 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Debug NuBus.sln
  - REPO_COMMIT_AUTHOR=$(git show -s --pretty=format:"%cn")
  - REPO_COMMIT_AUTHOR_EMAIL=$(git show -s --pretty=format:"%ce")
  - REPO_COMMIT_MESSAGE=$(git show -s --pretty=format:"%s")
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_BRANCH
  - echo $REPO_COMMIT_AUTHOR
  - echo $REPO_COMMIT_AUTHOR_EMAIL
  - echo $REPO_COMMIT_MESSAGE
  - echo $TRAVIS_JOB_ID
  - mono --debug --profile=monocov:outfile=monocovCoverage.cov,+NuBus ./testrunner/NUnit.ConsoleRunner.3.5.0/tools/nunit3-console.exe --process=Single ./NuBusTest/bin/Debug/NuBus.Test.dll

after_success:
  - cat monocovCoverage.cov
  - ls monocovCoverage
  - monocov --export-xml=monocovCoverage monocovCoverage.cov
