language: csharp
solution: NuBus.sln
install:
  - nuget restore NuBus.sln
  - nuget install NUnit.Runners -Version 3.5.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Debug NuBus.sln
  - mono ./testrunner/NUnit.Runners.3.5.0/tools/nunit-console.exe ./NuBus/NuBusTest/bin/Debug/NuBus.Test.dll
